version: '3.3'

networks:
  testtask_1-network:
    driver: bridge

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    image: postgres:12.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker
    networks:
      - testtask_1-network

  ap:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp
    container_name: webapp
    restart: always
    ports:
      - 5000:5000
    environment:
      PORT: 5000

      DATABASE_URL: "postgresql://postgres:postgres@db/docker"
      APP_SETTINGS: config.ProductionConfig
    depends_on:
      - db
    networks:
      - testtask_1-network
